Repository TEAM-TEMPUS/tempus, pull requests merged in 2022-05, with the labels that each got.

#78 서비스 댓글 등록, 수정, 삭제 기능 구현
  front/css/screens/detailPage.css
  front/css/screens/productModify.css
  front/css/screens/productRegistration.css
  front/detailPage.html
  front/js/detailPageslick.js
  front/productRegistration.html
  tempusproject/src/main/java/dao/CommentDao.java
  tempusproject/src/main/java/dao/CommentDaoTest.java
  tempusproject/src/main/java/dto/CommentDto.java
  tempusproject/src/main/java/mysql/db/DbConnect.java
  tempusproject/src/main/webapp/crud/comments/deletion.jsp
  tempusproject/src/main/webapp/crud/comments/edit.jsp
  tempusproject/src/main/webapp/crud/comments/registration.jsp
Labels: 백엔드

#80 서비스 조회 (수정 페이지), 거래 등록
  front/css/screens/transaction.css
  front/html/headerfooter.html
  front/html/memberedit.html
  front/html/membersignup.html
  front/html/transaction.html
  tempusproject/src/main/java/datadao/GradeDao.java
  tempusproject/src/main/java/datadao/GradeDaoTest.java
  tempusproject/src/main/java/datadao/ServiceImageDao.java
  tempusproject/src/main/java/datadao/ServiceImgDaoTest.java
  tempusproject/src/main/java/datadao/ServiceInqueryDao.java
  tempusproject/src/main/java/datadao/ServiceInqueryDaoTest.java
  tempusproject/src/main/java/datadto/GradeDto.java
  tempusproject/src/main/java/datadto/ServiceImgDto.java
  tempusproject/src/main/java/datadto/ServiceInqueryDto.java
  tempusproject/src/main/webapp/crud/service/inquery.jsp
  tempusproject/src/main/webapp/crud/service/inqueryImg.jsp
  tempusproject/src/main/webapp/crud/transactions/registration.jsp
  tempusproject/src/main/webapp/css/screens/transaction.css
  tempusproject/src/main/webapp/img/basic-profile-image.png
  tempusproject/src/main/webapp/js/serviceNavigation.js
  tempusproject/src/main/webapp/transaction.html
Labels: 백엔드

#83 dao,dto 폴더 삭제(#81)
  tempusproject/src/main/java/dao/CommentDao.java
  tempusproject/src/main/java/dao/CommentDaoTest.java
  tempusproject/src/main/java/dto/CommentDto.java
Labels: 백엔드

#84 registration/edit/deletion.jsp 파일 import경로 수정(#81)
  tempusproject/src/main/webapp/crud/comments/deletion.jsp
  tempusproject/src/main/webapp/crud/comments/edit.jsp
  tempusproject/src/main/webapp/crud/comments/registration.jsp
Labels: 백엔드

#87 서비스 등록 jsp 페이지 기본 세팅
  tempusproject/src/main/webapp/css/screens/serviceList.css
  tempusproject/src/main/webapp/img/service-list__test-img-1.jpg
  tempusproject/src/main/webapp/img/service-list__test-img-2.jpg
  tempusproject/src/main/webapp/img/service-list__test-img-3.jpg
  tempusproject/src/main/webapp/serviceList.jsp
Labels: 백엔드

#89 기존 product->service로 이름 수정
  front/css/screens/serviceModify.css
  front/css/screens/serviceRegistration.css
  front/detailPage.html
  front/js/serviceModify.js
  front/js/serviceModifyslick.js
  front/js/serviceRegistration.js
  front/js/serviceRegistrationslick.js
  front/serviceModify.html
  front/serviceRegistration.html
  tempusproject/src/main/webapp/css/screens/serviceModify.css
  tempusproject/src/main/webapp/css/screens/serviceRegistration.css
  tempusproject/src/main/webapp/js/serviceModify.js
  tempusproject/src/main/webapp/js/serviceModifyslick.js
  tempusproject/src/main/webapp/js/serviceRegistration.js
  tempusproject/src/main/webapp/js/serviceRegistrationslick.js
Labels: 프론트엔드

#93 서비스 조회 (수정 페이지) jsp 합치기
  tempusproject/src/main/java/data/dao/service/ServiceImageDaoTest.java
  tempusproject/src/main/webapp/crud/service/inquery.jsp
  tempusproject/src/main/webapp/crud/service/inqueryImg.jsp
Labels: 리팩터링

#97 서비스 조회 (수정 페이지) jsp merge, dao, dto 수정
  tempusproject/src/main/java/data/dao/service/ServiceDao.java
  tempusproject/src/main/java/data/dto/service/ServiceInqueryDto.java
  tempusproject/src/main/webapp/crud/service/inquery.jsp
  tempusproject/src/main/webapp/transaction.jsp
Labels: 리팩터링

#98 서비스 목록페이지 기능 구현
  tempusproject/src/main/java/common/Grades.java
  tempusproject/src/main/java/data/dao/service/ServiceDao.java
  tempusproject/src/main/java/data/dao/service/ServiceDaoTest.java
  tempusproject/src/main/java/data/dto/service/ServiceInqueryDto.java
  tempusproject/src/main/webapp/css/screens/serviceList.css
  tempusproject/src/main/webapp/img/status_completion.svg
  tempusproject/src/main/webapp/img/status_reservation.svg
  tempusproject/src/main/webapp/serviceList.jsp
Labels: 백엔드

#129 fix : 서비스 상세 페이지 프로필 정보 눌렀을때 예약중일때 프로필 모달창 안뜨는 오류 수정(#128)
  tempusproject/src/main/webapp/js/detailPage.js
Labels: 백엔드
